/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tributum.view;

import javax.swing.ButtonGroup;

/**
 *
 * @author lucas
 */
public class MenuGUI extends javax.swing.JFrame {
    
    SalarioCeletistaGUI salarioCeletistaGui = new SalarioCeletistaGUI();
    FolhaDePagamentoCeletistaGUI folhaDePagamentoCeletistaGui 
            = new FolhaDePagamentoCeletistaGUI();
    
    SalarioPJGUI salarioPJGui = new SalarioPJGUI();
    FolhaDePagamentoPJGUI folhaDePagamentoPJGui
            = new FolhaDePagamentoPJGUI();
    
    
    /**
     * Creates new form MenuGUI
     */
    public MenuGUI() {
        initComponents();
        groupButton();
    }

    /*
     * Esse metodo e usado para que nao ocorra a situacao de dois
     * radio buttons serem selecionados ao mesmo tempo
     */
    private void groupButton() {
        ButtonGroup bg1 = new ButtonGroup();
        
        bg1.add(alteracaoPgtoRadioButton);
        bg1.add(calculoPgtoRadioButton);
    }    
    
    private void fechaTelaAtual() {
        // Fecha tela atual
        setVisible(false);
        dispose();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        alteracaoPgtoRadioButton = new javax.swing.JRadioButton();
        calculoPgtoRadioButton = new javax.swing.JRadioButton();
        confirmarButton = new javax.swing.JButton();
        sairButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        alteracaoPgtoRadioButton.setText("Alterar valor do pagamento");
        alteracaoPgtoRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alteracaoPgtoRadioButtonActionPerformed(evt);
            }
        });

        calculoPgtoRadioButton.setSelected(true);
        calculoPgtoRadioButton.setText("Calcular pagamento");
        calculoPgtoRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculoPgtoRadioButtonActionPerformed(evt);
            }
        });

        confirmarButton.setText("Confirmar");
        confirmarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmarButtonActionPerformed(evt);
            }
        });

        sairButton.setText("Sair");
        sairButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(calculoPgtoRadioButton)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(confirmarButton)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(sairButton))
                        .addComponent(alteracaoPgtoRadioButton)))
                .addContainerGap(97, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(alteracaoPgtoRadioButton)
                .addGap(35, 35, 35)
                .addComponent(calculoPgtoRadioButton)
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(confirmarButton)
                    .addComponent(sairButton))
                .addContainerGap(73, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void alteracaoPgtoRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alteracaoPgtoRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_alteracaoPgtoRadioButtonActionPerformed

    private void calculoPgtoRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculoPgtoRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_calculoPgtoRadioButtonActionPerformed
    
    /* Essa tela eh usada tanto para Celetistas quanto para Pessoa Juridica.
     * Por conta disso eh necessario definir qual desses 
     * dois tipos estão em execução 
     */
    private void confirmarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmarButtonActionPerformed
        // Caso seja celetista
        if(TipoDeColaboradorGUI.botaoAtivo == 1) {
            if(alteracaoPgtoRadioButton.isSelected()) {
                salarioCeletistaGui.setVisible(true);
               // fechaTelaAtual();
            }
            else {
                folhaDePagamentoCeletistaGui.setVisible(true);
               // fechaTelaAtual();
            }
        }
        // Caso seja PJ
        else {
            if(alteracaoPgtoRadioButton.isSelected()) {
                salarioPJGui.setVisible(true);
                //fechaTelaAtual();
            }
            else {
                folhaDePagamentoPJGui.setVisible(true);
                //fechaTelaAtual();
            }
        }
    }//GEN-LAST:event_confirmarButtonActionPerformed

    private void sairButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairButtonActionPerformed
        dispose();
    }//GEN-LAST:event_sairButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MenuGUI menuGui = new MenuGUI();
                menuGui.setTitle("Menu");
                menuGui.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton alteracaoPgtoRadioButton;
    private javax.swing.JRadioButton calculoPgtoRadioButton;
    private javax.swing.JButton confirmarButton;
    private javax.swing.JButton sairButton;
    // End of variables declaration//GEN-END:variables
}
